const vocab = [
    { kanji: "日本", furigana: "にほん", arti: "Jepang" },
    { kanji: "腰", furigana: "こし", arti: "pinggang, punggung bawah" },
    { kanji: "曲げる", furigana: "まげる", arti: "membungkukkan, menekuk" },
    { kanji: "頭", furigana: "あたま", arti: "kepala" },
    { kanji: "前", furigana: "まえ", arti: "depan" },
    { kanji: "下げる", furigana: "さげる", arti: "menurunkan" },
    { kanji: "お礼", furigana: "おれい", arti: "ucapan terima kasih" },
    { kanji: "使う", furigana: "つかう", arti: "menggunakan" },
    { kanji: "角度", furigana: "かくど", arti: "sudut" },
    { kanji: "大きい", furigana: "おおきい", arti: "besar" },
    { kanji: "敬意", furigana: "けいい", arti: "rasa hormat" },
    { kanji: "高い", furigana: "たかい", arti: "tinggi" },
    { kanji: "道", furigana: "みち", arti: "jalan" },
    { kanji: "知り合い", furigana: "しりあい", arti: "kenalan" },
    { kanji: "会う", furigana: "あう", arti: "bertemu" },
    { kanji: "首", furigana: "くび", arti: "leher" },
    { kanji: "少し", furigana: "すこし", arti: "sedikit" },
    { kanji: "人", furigana: "ひと", arti: "orang" },
    { kanji: "握手", furigana: "あくしゅ", arti: "berjabat tangan" },
    { kanji: "世界", furigana: "せかい", arti: "dunia" },
    { kanji: "一般的", furigana: "いっぱんてき", arti: "umum" },
    { kanji: "両手", furigana: "りょうて", arti: "kedua tangan" },
    { kanji: "胸", furigana: "むね", arti: "dada" },
    { kanji: "合わせる", furigana: "あわせる", arti: "menyatukan, menggabungkan" },
    { kanji: "飯", furigana: "はん", arti: "nasi, makanan" },
    { kanji: "食べる", furigana: "たべる", arti: "makan" },
    { kanji: "普通", furigana: "ふつう", arti: "biasanya, normal" },
    { kanji: "誤解", furigana: "ごかい", arti: "kesalahpahaman" },
    { kanji: "少ない", furigana: "すくない", arti: "sedikit, tidak banyak" },
    { kanji: "日本語", furigana: "にほんご", arti: "bahasa Jepang" },
    { kanji: "別れ", furigana: "わかれ", arti: "perpisahan" },
    { kanji: "実際", furigana: "じっさい", arti: "kenyataannya, sebenarnya" },
    { kanji: "日常生活", furigana: "にちじょうせいかつ", arti: "kehidupan sehari-hari" },
    { kanji: "学校", furigana: "がっこう", arti: "sekolah" },
    { kanji: "生徒", furigana: "せいと", arti: "siswa" },
    { kanji: "先生", furigana: "せんせい", arti: "guru" },
    { kanji: "間", furigana: "あいだ", arti: "antara" },
    { kanji: "告げる", furigana: "つげる", arti: "menyampaikan, mengucapkan" },
    { kanji: "場面", furigana: "ばめん", arti: "situasi, adegan" },
    { kanji: "多い", furigana: "おおい", arti: "banyak" },
    { kanji: "教科書", furigana: "きょうかしょ", arti: "buku pelajaran" },
    { kanji: "本文", furigana: "ほんぶん", arti: "teks utama" },
    { kanji: "練習", furigana: "れんしゅう", arti: "latihan" },
    { kanji: "失礼", furigana: "しつれい", arti: "tidak sopan, permisi" },
    { kanji: "言い方", furigana: "いいかた", arti: "cara mengucapkan, ungkapan" },
    { kanji: "謝る", furigana: "あやまる", arti: "meminta maaf" },
    { kanji: "場合", furigana: "ばあい", arti: "kasus, situasi" },
    { kanji: "落とし物", furigana: "おとしもの", arti: "barang hilang" },
    { kanji: "拾う", furigana: "ひろう", arti: "memungut" },
    { kanji: "席", furigana: "せき", arti: "kursi, tempat duduk" },
    { kanji: "譲る", furigana: "ゆずる", arti: "memberikan, mengalah" },
    { kanji: "出てくる", furigana: "でてくる", arti: "muncul" },
    { kanji: "自分", furigana: "じぶん", arti: "diri sendiri" },
    { kanji: "相手", furigana: "あいて", arti: "lawan bicara, pihak lain" },
    { kanji: "不利益", furigana: "ふりえき", arti: "kerugian" },
    { kanji: "負担", furigana: "ふたん", arti: "beban" },
    { kanji: "感じる", furigana: "かんじる", arti: "merasakan" },
    { kanji: "礼", furigana: "れい", arti: "terima kasih, penghormatan" },
    { kanji: "表す", furigana: "あらわす", arti: "menyatakan, menunjukkan" },
    { kanji: "意味", furigana: "いみ", arti: "arti, makna" },
    { kanji: "例えば", furigana: "たとえば", arti: "misalnya" },
    { kanji: "祝い", furigana: "いわい", arti: "ucapan selamat, perayaan" },
    { kanji: "言う", furigana: "いう", arti: "mengatakan" },
    { kanji: "使い分け", furigana: "つかいわけ", arti: "penggunaan yang dibedakan sesuai situasi" },
    { kanji: "難しい", furigana: "むずかしい", arti: "sulit" },
    { kanji: "大丈夫", furigana: "だいじょうぶ", arti: "tidak masalah, baik-baik saja" },
    { kanji: "略語", furigana: "りゃくご", arti: "singkatan" },
    { kanji: "省略", furigana: "しょうりゃく", arti: "penyingkatan" },
    { kanji: "作る", furigana: "つくる", arti: "membuat" },
    { kanji: "後ろ", furigana: "うしろ", arti: "belakang" },
    { kanji: "部分", furigana: "ぶぶん", arti: "bagian" },
    { kanji: "複合語", furigana: "ふくごうご", arti: "kata majemuk" },
    { kanji: "文字", furigana: "もじ", arti: "huruf, karakter" },
    { kanji: "組み合わせる", furigana: "くみあわせる", arti: "menggabungkan" },
    { kanji: "外来語", furigana: "がいらいご", arti: "kata serapan" },
    { kanji: "見られる", furigana: "みられる", arti: "terlihat, ditemukan" },
    { kanji: "漢字", furigana: "かんじ", arti: "huruf kanji" },
    { kanji: "人名", furigana: "じんめい", arti: "nama orang" },
    { kanji: "以下", furigana: "いか", arti: "berikut ini" },
    { kanji: "例", furigana: "れい", arti: "contoh" },
    { kanji: "紹介", furigana: "しょうかい", arti: "memperkenalkan" },
    { kanji: "蚊", furigana: "か", arti: "nyamuk" },
    { kanji: "夏", furigana: "なつ", arti: "musim panas" },
    { kanji: "発生", furigana: "はっせい", arti: "muncul, berkembang" },
    { kanji: "特に", furigana: "とくに", arti: "terutama" },
    { kanji: "夕方", furigana: "ゆうがた", arti: "sore hari" },
    { kanji: "外", furigana: "そと", arti: "luar" },
    { kanji: "寄る", furigana: "よる", arti: "mendekat" },
    { kanji: "血", furigana: "ち", arti: "darah" },
    { kanji: "吸う", furigana: "すう", arti: "mengisap" },
    { kanji: "刺される", furigana: "さされる", arti: "disengat, digigit" },
    { kanji: "非常に", furigana: "ひじょうに", arti: "sangat" },
    { kanji: "熱", furigana: "ねつ", arti: "demam, panas" },
    { kanji: "伝染病", furigana: "でんせんびょう", arti: "penyakit menular" },
    { kanji: "媒介", furigana: "ばいかい", arti: "perantara, media penularan" },
    { kanji: "心配", furigana: "しんぱい", arti: "khawatir" },
    { kanji: "必要", furigana: "ひつよう", arti: "perlu, kebutuhan" },
    { kanji: "防ぐ", furigana: "ふせぐ", arti: "mencegah" },
    { kanji: "方法", furigana: "ほうほう", arti: "cara, metode" },
    { kanji: "手", furigana: "て", arti: "tangan" },
    { kanji: "足", furigana: "あし", arti: "kaki" },
    { kanji: "虫除け", furigana: "むしよけ", arti: "penolak serangga" },
    { kanji: "蚊取り線香", furigana: "かとりせんこう", arti: "obat nyamuk bakar" },
    { kanji: "殺す", furigana: "ころす", arti: "membunuh" },
    { kanji: "成分", furigana: "せいぶん", arti: "kandungan, komponen" },
    { kanji: "入る", furigana: "はいる", arti: "masuk" },
    { kanji: "線香", furigana: "せんこう", arti: "dupa" },
    { kanji: "伝統的", furigana: "でんとうてき", arti: "tradisional" },
    { kanji: "強い", furigana: "つよい", arti: "kuat" },
    { kanji: "灰", furigana: "はい", arti: "abu" },
    { kanji: "始末", furigana: "しまつ", arti: "penanganan, membereskan" },
    { kanji: "大変", furigana: "たいへん", arti: "sulit, berat" },
    { kanji: "現在", furigana: "げんざい", arti: "saat ini" },
    { kanji: "電気式", furigana: "でんきしき", arti: "tipe elektrik" },
    { kanji: "買う", furigana: "かう", arti: "membeli" },
    { kanji: "言語", furigana: "げんご", arti: "bahasa" },
    { kanji: "最も", furigana: "もっとも", arti: "paling" },
    { kanji: "複雑", furigana: "ふくざつ", arti: "rumit" },
    { kanji: "文字体系", furigana: "もじたいけい", arti: "sistem tulisan" },
    { kanji: "持つ", furigana: "もつ", arti: "memiliki" },
    { kanji: "複数", furigana: "ふくすう", arti: "lebih dari satu" },
    { kanji: "種類", furigana: "しゅるい", arti: "jenis" },
    { kanji: "中国", furigana: "ちゅうごく", arti: "Tiongkok" },
    { kanji: "起源", furigana: "きげん", arti: "asal-usul" },
    { kanji: "基本的", furigana: "きほんてき", arti: "pada dasarnya" },
    { kanji: "書く", furigana: "かく", arti: "menulis" },
    { kanji: "担う", furigana: "になう", arti: "memikul, menjalankan peran" },
    { kanji: "表す", furigana: "あらわす", arti: "menunjukkan, menyatakan" },
    { kanji: "読み方", furigana: "よみかた", arti: "cara membaca" },
    { kanji: "特徴", furigana: "とくちょう", arti: "ciri khas" },
    { kanji: "日曜日", furigana: "にちようび", arti: "hari Minggu" },
    { kanji: "違う", furigana: "ちがう", arti: "berbeda" },
    { kanji: "読む", furigana: "よむ", arti: "membaca" },
    { kanji: "崩す", furigana: "くずす", arti: "merombak, menyederhanakan" },
    { kanji: "平安時代", furigana: "へいあんじだい", arti: "Zaman Heian" },
    { kanji: "初期", furigana: "しょき", arti: "masa awal" },
    { kanji: "主に", furigana: "おもに", arti: "terutama" },
    { kanji: "助詞", furigana: "じょし", arti: "partikel" },
    { kanji: "動詞", furigana: "どうし", arti: "kata kerja" },
    { kanji: "形容詞", furigana: "けいようし", arti: "kata sifat" },
    { kanji: "語尾", furigana: "ごび", arti: "akhiran kata" },
    { kanji: "文法的", furigana: "ぶんぽうてき", arti: "gramatikal" },
    { kanji: "働き", furigana: "はたらき", arti: "fungsi, peran" },
    { kanji: "一部", furigana: "いちぶ", arti: "sebagian" },
    { kanji: "時期", furigana: "じき", arti: "periode, masa" },
    { kanji: "外国", furigana: "がいこく", arti: "negara asing" },
    { kanji: "地名", furigana: "ちめい", arti: "nama tempat" },
    { kanji: "動物", furigana: "どうぶつ", arti: "hewan" },
    { kanji: "植物", furigana: "しょくぶつ", arti: "tumbuhan" },
    { kanji: "名前", furigana: "なまえ", arti: "nama" },
    { kanji: "俗語", furigana: "ぞくご", arti: "bahasa gaul, slang" },
    { kanji: "固有名詞", furigana: "こゆうめいし", arti: "kata benda khusus" },
    { kanji: "来る", furigana: "くる", arti: "datang" },
    { kanji: "外国人", furigana: "がいこくじん", arti: "orang asing" },
    { kanji: "駅名", furigana: "えきめい", arti: "nama stasiun" },
    { kanji: "日常的", furigana: "にちじょうてき", arti: "sehari-hari, rutin" },
    { kanji: "字", furigana: "じ", arti: "huruf, karakter" },
    { kanji: "同じ", furigana: "おなじ", arti: "sama" },
    { kanji: "外す", furigana: "はずす", arti: "melepas, menghilangkan" },
    { kanji: "読まれる", furigana: "よまれる", arti: "dibaca" },
    { kanji: "書かれる", furigana: "かかれる", arti: "ditulis" },
    { kanji: "使われる", furigana: "つかわれる", arti: "digunakan" },
    { kanji: "表した", furigana: "あらわした", arti: "yang dituliskan, diekspresikan" },
    { kanji: "駅", furigana: "えき", arti: "stasiun" },
    { kanji: "呼び方", furigana: "よびかた", arti: "cara memanggil" },
    { kanji: "後ろ", furigana: "うしろ", arti: "belakang, setelah" },
    { kanji: "普通", furigana: "ふつう", arti: "biasa, umum" },
    { kanji: "男性", furigana: "だんせい", arti: "laki-laki" },
    { kanji: "女性", furigana: "じょせい", arti: "perempuan" },
    { kanji: "年上", furigana: "としうえ", arti: "orang yang lebih tua" },
    { kanji: "年下", furigana: "としした", arti: "orang yang lebih muda" },
    { kanji: "結婚", furigana: "けっこん", arti: "pernikahan" },
    { kanji: "関係", furigana: "かんけい", arti: "hubungan, kaitan" },
    { kanji: "非常", furigana: "ひじょう", arti: "sangat" },
    { kanji: "便利", furigana: "べんり", arti: "praktis, nyaman" },
    { kanji: "日本人", furigana: "にほんじん", arti: "orang Jepang" },
    { kanji: "前", furigana: "まえ", arti: "sebelum, depan" },
    { kanji: "苗字", furigana: "みょうじ", arti: "nama keluarga" },
    { kanji: "下", furigana: "した", arti: "bawah" },
    { kanji: "家族", furigana: "かぞく", arti: "keluarga" },
    { kanji: "親しい", furigana: "したしい", arti: "akrab" },
    { kanji: "友人", furigana: "ゆうじん", arti: "teman" },
    { kanji: "同士", furigana: "どうし", arti: "sesama" },
    { kanji: "仕事", furigana: "しごと", arti: "pekerjaan" },
    { kanji: "場面", furigana: "ばめん", arti: "situasi" },
    { kanji: "本人", furigana: "ほんにん", arti: "orang yang bersangkutan" },
    { kanji: "君", furigana: "くん", arti: "sufiks untuk laki-laki muda" },
    { kanji: "様", furigana: "さま", arti: "Tuan/Nyonya (sangat sopan)" },
    { kanji: "同年代", furigana: "どうねんだい", arti: "generasi/seusia" },
    { kanji: "子ども", furigana: "こども", arti: "anak" },
    { kanji: "親しみ", furigana: "したしみ", arti: "keakraban" },
    { kanji: "込める", furigana: "こめる", arti: "mencurahkan, memasukkan perasaan" },
    { kanji: "丁寧", furigana: "ていねい", arti: "sopan" },
    { kanji: "敬称", furigana: "けいしょう", arti: "gelar kehormatan" },
    { kanji: "店", furigana: "みせ", arti: "toko" },
    { kanji: "客", furigana: "きゃく", arti: "pelanggan, tamu" },
    { kanji: "元号", furigana: "げんごう", arti: "nama era Jepang" },
    { kanji: "西暦", furigana: "せいれき", arti: "kalender Masehi" },
    { kanji: "役所", furigana: "やくしょ", arti: "kantor pemerintahan" },
    { kanji: "公的", furigana: "こうてき", arti: "resmi, publik" },
    { kanji: "文書", furigana: "ぶんしょ", arti: "dokumen" },
    { kanji: "独自", furigana: "どくじ", arti: "khas, unik" },
    { kanji: "年号", furigana: "ねんごう", arti: "nama tahun/era" },
    { kanji: "令和", furigana: "れいわ", arti: "Era Reiwa" },
    { kanji: "番目", furigana: "ばんめ", arti: "urutan ke-" },
    { kanji: "新しい", furigana: "あたらしい", arti: "baru" },
    { kanji: "天皇", furigana: "てんのう", arti: "Kaisar Jepang" },
    { kanji: "即位", furigana: "そくい", arti: "naik takhta" },
    { kanji: "年", furigana: "とし", arti: "tahun" },
    { kanji: "昭和", furigana: "しょうわ", arti: "Era Shōwa" },
    { kanji: "代表", furigana: "だいひょう", arti: "mewakili" },
    { kanji: "歌", furigana: "うた", arti: "lagu" },
    { kanji: "平成", furigana: "へいせい", arti: "Era Heisei" },
    { kanji: "大不況", furigana: "だいふきょう", arti: "resesi besar" },
    { kanji: "時代", furigana: "じだい", arti: "zaman, era" },
    { kanji: "生活", furigana: "せいかつ", arti: "kehidupan" },
    { kanji: "根付く", furigana: "ねづく", arti: "berakar, mengakar" },
    { kanji: "以下", furigana: "いか", arti: "berikut" },
    { kanji: "表", furigana: "ひょう", arti: "tabel" },
    { kanji: "対照表", furigana: "たいしょうひょう", arti: "tabel perbandingan" },
    { kanji: "生まれる", furigana: "うまれる", arti: "lahir" },
    { kanji: "何年", furigana: "なんねん", arti: "tahun berapa" },
    { kanji: "驚かす", furigana: "おどろかす", arti: "membuat terkejut" },
    { kanji: "元年", furigana: "がんねん", arti: "tahun pertama suatu era" },
    { kanji: "主な", furigana: "おもな", arti: "utama" },
    { kanji: "都市", furigana: "とし", arti: "kota" },
    { kanji: "東京", furigana: "とうきょう", arti: "Tokyo" },
    { kanji: "首都", furigana: "しゅと", arti: "ibu kota" },
    { kanji: "東京都区部", furigana: "とうきょうとくぶ", arti: "wilayah 23 distrik Tokyo" },
    { kanji: "人口", furigana: "じんこう", arti: "populasi" },
    { kanji: "約", furigana: "やく", arti: "sekitar" },
    { kanji: "人口密度", furigana: "じんこうみつど", arti: "kepadatan penduduk" },
    { kanji: "日本一", furigana: "にほんいち", arti: "nomor satu di Jepang" },
    { kanji: "政治", furigana: "せいじ", arti: "politik" },
    { kanji: "経済", furigana: "けいざい", arti: "ekonomi" },
    { kanji: "中心", furigana: "ちゅうしん", arti: "pusat" },
    { kanji: "県", furigana: "けん", arti: "prefektur" },
    { kanji: "権限", furigana: "けんげん", arti: "wewenang" },
    { kanji: "与える", furigana: "あたえる", arti: "memberikan" },
    { kanji: "大都市", furigana: "だいとし", arti: "kota besar" },
    { kanji: "政令指定都市", furigana: "せいれいしていとし", arti: "kota yang ditetapkan melalui peraturan pemerintah" },
    { kanji: "全部", furigana: "ぜんぶ", arti: "seluruhnya" },
    { kanji: "地図", furigana: "ちず", arti: "peta" },
    { kanji: "以上", furigana: "いじょう", arti: "lebih dari" },
    { kanji: "位置", furigana: "いち", arti: "posisi, letak" },
    { kanji: "覚える", furigana: "おぼえる", arti: "menghafal, mengingat" },
    { kanji: "役に立つ", furigana: "やくにたつ", arti: "bermanfaat" },
    { kanji: "立つ", furigana: "たつ", arti: "berdiri; berguna (dalam ungkapan)" },
    { kanji: "年齢", furigana: "ねんれい", arti: "usia" },
    { kanji: "聞く", furigana: "きく", arti: "bertanya, mendengar" },
    { kanji: "国", furigana: "くに", arti: "negara" },
    { kanji: "失礼", furigana: "しつれい", arti: "tidak sopan" },
    { kanji: "信じる", furigana: "しんじる", arti: "percaya" },
    { kanji: "文化", furigana: "ぶんか", arti: "budaya" },
    { kanji: "一方", furigana: "いっぽう", arti: "di sisi lain" },
    { kanji: "気軽", furigana: "きがる", arti: "santai, tanpa sungkan" },
    { kanji: "考える", furigana: "かんがえる", arti: "berpikir, menganggap" },
    { kanji: "文化圏", furigana: "ぶんかけん", arti: "lingkup budaya" },
    { kanji: "比べる", furigana: "くらべる", arti: "membandingkan" },
    { kanji: "機会", furigana: "きかい", arti: "kesempatan" },
    { kanji: "理由", furigana: "りゆう", arti: "alasan" },
    { kanji: "目上", furigana: "めうえ", arti: "orang yang lebih tinggi kedudukannya/lebih tua" },
    { kanji: "目下", furigana: "めした", arti: "orang yang lebih rendah kedudukannya/lebih muda" },
    { kanji: "区別", furigana: "くべつ", arti: "pembedaan" },
    { kanji: "社会的", furigana: "しゃかいてき", arti: "bersifat sosial" },
    { kanji: "意味", furigana: "いみ", arti: "makna" },
    { kanji: "年上", furigana: "としうえ", arti: "lebih tua" },
    { kanji: "年下", furigana: "としした", arti: "lebih muda" },
    { kanji: "同年代", furigana: "どうねんだい", arti: "seusia" },
    { kanji: "使い分ける", furigana: "つかいわける", arti: "menggunakan secara berbeda sesuai situasi" },
    { kanji: "地方", furigana: "ちほう", arti: "daerah" },
    { kanji: "年代", furigana: "ねんだい", arti: "generasi, kelompok usia" },
    { kanji: "意識", furigana: "いしき", arti: "kesadaran" },
    { kanji: "本当", furigana: "ほんとう", arti: "sebenarnya" },
    { kanji: "答える", furigana: "こたえる", arti: "menjawab" },
    { kanji: "秘密", furigana: "ひみつ", arti: "rahasia" },
    { kanji: "歳", furigana: "さい", arti: "tahun usia" },
    { kanji: "冗談", furigana: "じょうだん", arti: "lelucon, bercanda" },
    { kanji: "何歳", furigana: "なんさい", arti: "berapa usia" },
    { kanji: "見える", furigana: "みえる", arti: "terlihat" },
    { kanji: "逆", furigana: "ぎゃく", arti: "kebalikan" },
    { kanji: "質問", furigana: "しつもん", arti: "pertanyaan" },
    { kanji: "直接的", furigana: "ちょくせつてき", arti: "secara langsung" },
    { kanji: "相手", furigana: "あいて", arti: "lawan bicara" },
    { kanji: "知る", furigana: "しる", arti: "mengetahui" },
    { kanji: "干支", furigana: "えと", arti: "shio" },
    { kanji: "支", furigana: "し", arti: "cabang zodiak (12 shio)" },
    { kanji: "概念", furigana: "がいねん", arti: "konsep" },
    { kanji: "順番", furigana: "じゅんばん", arti: "urutan" },
    { kanji: "割り振る", furigana: "わりふる", arti: "membagi, mengalokasikan" },
    { kanji: "生まれ", furigana: "うまれ", arti: "kelahiran" },
    { kanji: "度", furigana: "ど", arti: "kali, derajat" },
    { kanji: "西暦", furigana: "せいれき", arti: "tahun Masehi" },
    { kanji: "推測", furigana: "すいそく", arti: "perkiraan" },
    { kanji: "知らない", furigana: "しらない", arti: "tidak tahu" },
    { kanji: "覚える", furigana: "おぼえる", arti: "mengingat, menghafal" },
    { kanji: "海", furigana: "うみ", arti: "laut" },
    { kanji: "島国", furigana: "しまぐに", arti: "negara kepulauan" },
    { kanji: "囲まれる", furigana: "かこまれる", arti: "dikelilingi" },
    { kanji: "友だち", furigana: "ともだち", arti: "teman" },
    { kanji: "海水浴", furigana: "かいすいよく", arti: "berenang/mandi di laut" },
    { kanji: "出かける", furigana: "でかける", arti: "pergi keluar" },
    { kanji: "沖縄", furigana: "おきなわ", arti: "Okinawa" },
    { kanji: "月", furigana: "がつ", arti: "bulan" },
    { kanji: "泳ぐ", furigana: "およぐ", arti: "berenang" },
    { kanji: "海水浴場", furigana: "かいすいよくじょう", arti: "pantai tempat berenang" },
    { kanji: "設置", furigana: "せっち", arti: "pemasangan, penyediaan" },
    { kanji: "楽しむ", furigana: "たのしむ", arti: "menikmati" },
    { kanji: "海の家", furigana: "うみのいえ", arti: "pondok/fasilitas di pantai" },
    { kanji: "海岸", furigana: "かいがん", arti: "pantai, pesisir" },
    { kanji: "休憩", furigana: "きゅうけい", arti: "istirahat" },
    { kanji: "食事", furigana: "しょくじ", arti: "makan, hidangan" },
    { kanji: "提供", furigana: "ていきょう", arti: "menyediakan" },
    { kanji: "施設", furigana: "しせつ", arti: "fasilitas" },
    { kanji: "南", furigana: "みなみ", arti: "selatan" },
    { kanji: "一年中", furigana: "いちねんじゅう", arti: "sepanjang tahun" },
    { kanji: "暖かい", furigana: "あたたかい", arti: "hangat" },
    { kanji: "青い", furigana: "あおい", arti: "biru" },
    { kanji: "白い", furigana: "しろい", arti: "putih" },
    { kanji: "珊瑚", furigana: "さんご", arti: "karang (coral)" },
    { kanji: "砂浜", furigana: "すなはま", arti: "pantai berpasir" },
    { kanji: "美しい", furigana: "うつくしい", arti: "indah" },
    { kanji: "人気", furigana: "にんき", arti: "populer" },
    { kanji: "幸", furigana: "さち", arti: "hasil alam, karunia" },
    { kanji: "旅行", furigana: "りょこう", arti: "perjalanan, wisata" },
    { kanji: "楽しみ", furigana: "たのしみ", arti: "kesenangan" },
    { kanji: "近く", furigana: "ちかく", arti: "dekat" },
    { kanji: "漁港", furigana: "ぎょこう", arti: "pelabuhan nelayan" },
    { kanji: "魚市場", furigana: "うおいちば", arti: "pasar ikan" },
    { kanji: "新鮮", furigana: "しんせん", arti: "segar" },
    { kanji: "魚介類", furigana: "ぎょかいるい", arti: "makanan laut" },
    { kanji: "町", furigana: "まち", arti: "kota kecil" },
    { kanji: "行く", furigana: "いく", arti: "pergi" },
    { kanji: "土地", furigana: "とち", arti: "daerah, wilayah" },
    { kanji: "刺身", furigana: "さしみ", arti: "sashimi" },
    { kanji: "寿司", furigana: "すし", arti: "sushi" },
    { kanji: "生", furigana: "なま", arti: "mentah" },
    { kanji: "魚", furigana: "さかな", arti: "ikan" },
    { kanji: "薄い", furigana: "うすい", arti: "tipis" },
    { kanji: "切る", furigana: "きる", arti: "memotong" },
    { kanji: "料理", furigana: "りょうり", arti: "masakan, hidangan" },
    { kanji: "代表的", furigana: "だいひょうてき", arti: "khas, representatif" },
    { kanji: "日本料理", furigana: "にほんりょうり", arti: "masakan Jepang" },
    { kanji: "切り身", furigana: "きりみ", arti: "potongan fillet ikan" },
    { kanji: "並べる", furigana: "ならべる", arti: "menyusun, menata" },
    { kanji: "見た目", furigana: "みため", arti: "penampilan" },
    { kanji: "盛り付ける", furigana: "もりつける", arti: "menyajikan, menata makanan" },
    { kanji: "細い", furigana: "ほそい", arti: "tipis, ramping" },
    { kanji: "大根", furigana: "だいこん", arti: "lobak putih" },
    { kanji: "海藻", furigana: "かいそう", arti: "rumput laut" },
    { kanji: "置く", furigana: "おく", arti: "meletakkan" },
    { kanji: "残す", furigana: "のこす", arti: "menyisakan" },
    { kanji: "酢飯", furigana: "すめし", arti: "nasi bercuka untuk sushi" },
    { kanji: "世界中", furigana: "せかいじゅう", arti: "seluruh dunia" },
    { kanji: "広まる", furigana: "ひろまる", arti: "menyebar" },
    { kanji: "巻き寿司", furigana: "まきずし", arti: "sushi gulung" },
    { kanji: "押し寿司", furigana: "おしずし", arti: "sushi tekan" },
    { kanji: "本格的", furigana: "ほんかくてき", arti: "autentik, serius" },
    { kanji: "寿司屋", furigana: "すしや", arti: "restoran sushi" },
    { kanji: "高い", furigana: "たかい", arti: "mahal, tinggi" },
    { kanji: "料金", furigana: "りょうきん", arti: "biaya, tarif" },
    { kanji: "値段", furigana: "ねだん", arti: "harga" },
    { kanji: "抑える", furigana: "おさえる", arti: "menekan, mengurangi" },
    { kanji: "店", furigana: "みせ", arti: "toko, restoran" },
    { kanji: "回転寿司", furigana: "かいてんずし", arti: "sushi putar" },
    { kanji: "運ぶ", furigana: "はこぶ", arti: "mengangkut, membawa" },
    { kanji: "比較的", furigana: "ひかくてき", arti: "relatif" },
    { kanji: "安い", furigana: "やすい", arti: "murah" },
    { kanji: "気軽", furigana: "きがる", arti: "santai, mudah" },
    { kanji: "天ぷら", furigana: "てんぷら", arti: "tempura" },
    { kanji: "野菜", furigana: "やさい", arti: "sayuran" },
    { kanji: "小麦粉", furigana: "こむぎこ", arti: "tepung terigu" },
    { kanji: "衣", furigana: "ころも", arti: "adonan/pelapis gorengan" },
    { kanji: "油", furigana: "あぶら", arti: "minyak" },
    { kanji: "揚げる", furigana: "あげる", arti: "menggoreng" },
    { kanji: "料理", furigana: "りょうり", arti: "masakan" },
    { kanji: "語源", furigana: "ごげん", arti: "asal kata" },
    { kanji: "調味料", furigana: "ちょうみりょう", arti: "bumbu" },
    { kanji: "由来", furigana: "ゆらい", arti: "berasal dari" },
    { kanji: "塩", furigana: "しお", arti: "garam" },
    { kanji: "飯", furigana: "めし／はん", arti: "nasi" },
    { kanji: "上", furigana: "うえ", arti: "atas" },
    { kanji: "食べ方", furigana: "たべかた", arti: "cara makan" },
    { kanji: "和食", furigana: "わしょく", arti: "masakan Jepang" },
    { kanji: "麺類", furigana: "めんるい", arti: "mi dan sejenisnya" },
    { kanji: "太い", furigana: "ふとい", arti: "tebal" },
    { kanji: "麺", furigana: "めん", arti: "mi" },
    { kanji: "粉", furigana: "こな", arti: "tepung" },
    { kanji: "温かい", furigana: "あたたかい", arti: "hangat" },
    { kanji: "水", furigana: "みず", arti: "air" },
    { kanji: "冷やす", furigana: "ひやす", arti: "mendinginkan" },
    { kanji: "皿", furigana: "さら", arti: "piring" },
    { kanji: "盛る", furigana: "もる", arti: "menyajikan, menaruh" },
    { kanji: "濃い", furigana: "こい", arti: "kental, pekat" },
    { kanji: "一方", furigana: "いっぽう", arti: "salah satu sisi" },
    { kanji: "扱う", furigana: "あつかう", arti: "menangani, menjual" },
    { kanji: "専門的", furigana: "せんもんてき", arti: "khusus, spesialis" },
    { kanji: "多く", furigana: "おおく", arti: "banyak" },
    { kanji: "両方", furigana: "りょうほう", arti: "kedua-duanya" },
    { kanji: "選ぶ", furigana: "えらぶ", arti: "memilih" },
    { kanji: "電車", furigana: "でんしゃ", arti: "kereta listrik" },
    { kanji: "短い", furigana: "みじかい", arti: "pendek" },
    { kanji: "時間", furigana: "じかん", arti: "waktu" },
    { kanji: "提供", furigana: "ていきょう", arti: "penyediaan" },
    { kanji: "急ぐ", furigana: "いそぐ", arti: "terburu-buru" },
    { kanji: "便利", furigana: "べんり", arti: "praktis" },
    { kanji: "音", furigana: "おと", arti: "suara" },
    { kanji: "立てる", furigana: "たてる", arti: "membuat (suara)" },
    { kanji: "香り", furigana: "かおり", arti: "aroma" },
    { kanji: "伝える", furigana: "つたえる", arti: "menyampaikan" },
    { kanji: "具", furigana: "ぐ", arti: "isian, topping" },
    { kanji: "竹", furigana: "たけ", arti: "bambu" },
    { kanji: "編む", furigana: "あむ", arti: "menganyam" },
    { kanji: "器", furigana: "うつわ", arti: "wadah" },
    { kanji: "冷たい", furigana: "つめたい", arti: "dingin" },
    { kanji: "油揚げ", furigana: "あぶらあげ", arti: "tahu goreng tipis" },
    { kanji: "関西", furigana: "かんさい", arti: "Kansai" },
    { kanji: "月見", furigana: "つきみ", arti: "melihat bulan" },
    { kanji: "生卵", furigana: "なまたまご", arti: "telur mentah" },
    { kanji: "経由", furigana: "けいゆ", arti: "melalui" },
    { kanji: "明治時代", furigana: "めいじじだい", arti: "Zaman Meiji" },
    { kanji: "平均", furigana: "へいきん", arti: "rata-rata" },
    { kanji: "週", furigana: "しゅう", arti: "minggu" },
    { kanji: "度", furigana: "ど", arti: "kali" },
    { kanji: "定食屋", furigana: "ていしょくや", arti: "restoran set menu" },
    { kanji: "牛丼屋", furigana: "ぎゅうどんや", arti: "restoran gyudon" },
    { kanji: "飲食店", furigana: "いんしょくてん", arti: "restoran/tempat makan" },
    { kanji: "国民食", furigana: "こくみんしょく", arti: "makanan nasional" },
    { kanji: "市販", furigana: "しはん", arti: "dijual di pasaran" },
    { kanji: "簡単", furigana: "かんたん", arti: "mudah" },
    { kanji: "袋", furigana: "ふくろ", arti: "kantong" },
    { kanji: "湯", furigana: "ゆ", arti: "air panas" },
    { kanji: "食品", furigana: "しょくひん", arti: "produk makanan" },
    { kanji: "売る", furigana: "うる", arti: "menjual" },
    { kanji: "食事", furigana: "しょくじ", arti: "makan" },
    { kanji: "丼物", furigana: "どんぶりもの", arti: "hidangan nasi dalam mangkuk (donburi)" },
    { kanji: "丼", furigana: "どんぶり", arti: "mangkuk besar untuk nasi" },
    { kanji: "飯", furigana: "めし／はん", arti: "nasi, makanan" },
    { kanji: "入れる", furigana: "いれる", arti: "memasukkan" },
    { kanji: "具材", furigana: "ぐざい", arti: "bahan/isian makanan" },
    { kanji: "牛丼", furigana: "ぎゅうどん", arti: "donburi daging sapi" },
    { kanji: "品名", furigana: "ひんめい", arti: "nama produk/menu" },
    { kanji: "呼ぶ", furigana: "よぶ", arti: "menyebut, memanggil" },
    { kanji: "登場", furigana: "とうじょう", arti: "kemunculan" },
    { kanji: "牛肉", furigana: "ぎゅうにく", arti: "daging sapi" },
    { kanji: "炒める", furigana: "いためる", arti: "menumis" },
    { kanji: "甘辛い", furigana: "あまからい", arti: "manis dan gurih/asin" },
    { kanji: "味", furigana: "あじ", arti: "rasa" },
    { kanji: "紅", furigana: "べに", arti: "merah tua" },
    { kanji: "豚", furigana: "ぶた", arti: "babi" },
    { kanji: "豚カツ", furigana: "とんかつ", arti: "pork cutlet" },
    { kanji: "煮込む", furigana: "にこむ", arti: "merebus hingga meresap" },
    { kanji: "卵", furigana: "たまご", arti: "telur" },
    { kanji: "親子丼", furigana: "おやこどん", arti: "donburi ayam dan telur" },
    { kanji: "焼き鳥", furigana: "やきとり", arti: "sate ayam Jepang" },
    { kanji: "出す", furigana: "だす", arti: "menyajikan" },
    { kanji: "鶏肉", furigana: "とりにく", arti: "daging ayam" },
    { kanji: "親子", furigana: "おやこ", arti: "orang tua dan anak" },
    { kanji: "代わり", furigana: "かわり", arti: "pengganti" },
    { kanji: "豚肉", furigana: "ぶたにく", arti: "daging babi" },
    { kanji: "他人丼", furigana: "たにんどん", arti: "donburi telur dengan daging selain ayam" },
    { kanji: "載せる", furigana: "のせる", arti: "menaruh, mencantumkan" },
    { kanji: "海鮮丼", furigana: "かいせんどん", arti: "donburi seafood/sashimi" },
    { kanji: "鮭", furigana: "さけ", arti: "salmon" },
    { kanji: "等", furigana: "など", arti: "dan lain-lain" },
    { kanji: "鰻丼", furigana: "うなどん", arti: "donburi belut" },
    { kanji: "鰻", furigana: "うなぎ", arti: "belut" },
    { kanji: "蒲焼き", furigana: "かばやき", arti: "belut panggang dengan saus" },
    { kanji: "高級", furigana: "こうきゅう", arti: "kelas atas, mewah" },
    { kanji: "重箱", furigana: "じゅうばこ", arti: "kotak bertingkat untuk makanan" },
    { kanji: "鰻重", furigana: "うなじゅう", arti: "belut dalam kotak lacquer" },
    { kanji: "大きさ", furigana: "おおきさ", arti: "ukuran" },
    { kanji: "松", furigana: "まつ", arti: "pinus (peringkat tertinggi)" },
    { kanji: "竹", furigana: "たけ", arti: "bambu (peringkat menengah)" },
    { kanji: "梅", furigana: "うめ", arti: "plum (peringkat dasar)" },
    { kanji: "順位", furigana: "じゅんい", arti: "peringkat" },
    { kanji: "高い", furigana: "たかい", arti: "tinggi, mahal" },
    { kanji: "普通", furigana: "ふつう", arti: "biasa" },
    { kanji: "異なる", furigana: "ことなる", arti: "berbeda" },
    { kanji: "土用", furigana: "どよう", arti: "periode musiman tradisional" },
    { kanji: "丑の日", furigana: "うしのひ", arti: "Hari Kerbau (dalam kalender tradisional)" },
    { kanji: "習慣", furigana: "しゅうかん", arti: "kebiasaan" },
    { kanji: "日", furigana: "ひ", arti: "hari" },
    { kanji: "苦手", furigana: "にがて", arti: "tidak pandai, tidak suka" },
    { kanji: "食べ物", furigana: "たべもの", arti: "makanan" },
    { kanji: "中", furigana: "なか", arti: "di dalam" },
    { kanji: "納豆", furigana: "なっとう", arti: "natto" },
    { kanji: "梅干し", furigana: "うめぼし", arti: "acar plum asin" },
    { kanji: "居酒屋", furigana: "いざかや", arti: "pub/restoran Jepang" },
    { kanji: "塩辛", furigana: "しおから", arti: "makanan fermentasi asin dari seafood" },
    { kanji: "声", furigana: "こえ", arti: "suara, komentar" },
    { kanji: "聞く", furigana: "きく", arti: "mendengar" },
    { kanji: "好み", furigana: "このみ", arti: "selera, kesukaan" },
    { kanji: "試す", furigana: "ためす", arti: "mencoba" },
    { kanji: "大豆", furigana: "だいず", arti: "kedelai" },
    { kanji: "発酵", furigana: "はっこう", arti: "fermentasi" },
    { kanji: "独特", furigana: "どくとく", arti: "khas, unik" },
    { kanji: "糸", furigana: "いと", arti: "benang" },
    { kanji: "引く", furigana: "ひく", arti: "menarik" },
    { kanji: "粘り", furigana: "ねばり", arti: "kelengketan" },
    { kanji: "朝食", furigana: "ちょうしょく", arti: "sarapan" },
    { kanji: "関西", furigana: "かんさい", arti: "wilayah Kansai" },
    { kanji: "関東", furigana: "かんとう", arti: "wilayah Kanto" },
    { kanji: "典型", furigana: "てんけい", arti: "contoh khas, tipikal" },
    { kanji: "考える", furigana: "かんがえる", arti: "menganggap" },
    { kanji: "好き", furigana: "すき", arti: "suka" },
    { kanji: "感心", furigana: "かんしん", arti: "kagum" },
    { kanji: "驚く", furigana: "おどろく", arti: "terkejut" },
    { kanji: "梅", furigana: "うめ", arti: "plum Jepang" },
    { kanji: "実", furigana: "み", arti: "buah" },
    { kanji: "塩漬け", furigana: "しおづけ", arti: "diasinkan" },
    { kanji: "酸っぱい", furigana: "すっぱい", arti: "asam" },
    { kanji: "弁当", furigana: "べんとう", arti: "bekal makan" },
    { kanji: "茶漬け", furigana: "ちゃづけ", arti: "nasi dengan teh/kaldu" },
    { kanji: "健康食品", furigana: "けんこうしょくひん", arti: "makanan kesehatan" },
    { kanji: "身", furigana: "み", arti: "daging/bagian tubuh" },
    { kanji: "内臓", furigana: "ないぞう", arti: "organ dalam" },
    { kanji: "合わせる", furigana: "あわせる", arti: "mencampurkan" },
    { kanji: "刻む", furigana: "きざむ", arti: "mencincang" },
    { kanji: "酒", furigana: "さけ", arti: "alkohol, sake" },
    { kanji: "嫌い", furigana: "きらい", arti: "tidak suka" },
    { kanji: "気持ち", furigana: "きもち", arti: "perasaan" },
    { kanji: "悪い", furigana: "わるい", arti: "buruk" },
    { kanji: "無理", furigana: "むり", arti: "tidak sanggup, mustahil" },
    { kanji: "感想", furigana: "かんそう", arti: "kesan, pendapat" },
    { kanji: "日本酒", furigana: "にほんしゅ", arti: "sake Jepang" },
    { kanji: "米", furigana: "こめ", arti: "beras" },
    { kanji: "日本各地", furigana: "にほんかくち", arti: "berbagai daerah di Jepang" },
    { kanji: "酒蔵", furigana: "さかぐら", arti: "pabrik/gudang pembuatan sake" },
    { kanji: "日本全国", furigana: "にほんぜんこく", arti: "seluruh Jepang" },
    { kanji: "銘柄", furigana: "めいがら", arti: "merek, label" },
    { kanji: "造る", furigana: "つくる", arti: "memproduksi, membuat" },
    { kanji: "度数", furigana: "どすう", arti: "kadar alkohol" },
    { kanji: "酒", furigana: "さけ", arti: "alkohol, minuman keras" },
    { kanji: "指す", furigana: "さす", arti: "menunjuk, merujuk" },
    { kanji: "飲料", furigana: "いんりょう", arti: "minuman" },
    { kanji: "全体", furigana: "ぜんたい", arti: "keseluruhan" },
    { kanji: "人工的", furigana: "じんこうてき", arti: "buatan, artifisial" },
    { kanji: "米麹", furigana: "こめこうじ", arti: "koji beras" },
    { kanji: "純米酒", furigana: "じゅんまいしゅ", arti: "sake murni dari beras" },
    { kanji: "原料", furigana: "げんりょう", arti: "bahan baku" },
    { kanji: "削る", furigana: "けずる", arti: "mengikis, memoles" },
    { kanji: "芯", furigana: "しん", arti: "inti" },
    { kanji: "吟醸酒", furigana: "ぎんじょうしゅ", arti: "sake ginjo" },
    { kanji: "味わい", furigana: "あじわい", arti: "cita rasa" },
    { kanji: "甘口", furigana: "あまくち", arti: "rasa manis" },
    { kanji: "辛口", furigana: "からくち", arti: "rasa kering/tidak manis" },
    { kanji: "分ける", furigana: "わける", arti: "membagi" },
    { kanji: "成分", furigana: "せいぶん", arti: "komponen, kandungan" },
    { kanji: "残る", furigana: "のこる", arti: "tersisa" },
    { kanji: "比率", furigana: "ひりつ", arti: "perbandingan, rasio" },
    { kanji: "飲み方", furigana: "のみかた", arti: "cara minum" },
    { kanji: "冷酒", furigana: "れいしゅ", arti: "sake dingin" },
    { kanji: "温める", furigana: "あたためる", arti: "menghangatkan" },
    { kanji: "熱燗", furigana: "あつかん", arti: "sake hangat" },
    { kanji: "飲む", furigana: "のむ", arti: "minum" },
    { kanji: "最近", furigana: "さいきん", arti: "belakangan ini" },
    { kanji: "集める", furigana: "あつめる", arti: "mengumpulkan" },
    { kanji: "各地", furigana: "かくち", arti: "berbagai daerah" },
    { kanji: "地", furigana: "ち", arti: "daerah, wilayah" },
    { kanji: "典型的", furigana: "てんけいてき", arti: "tipikal" },
    { kanji: "飯", furigana: "はん／めし", arti: "nasi" },
    { kanji: "味噌汁", furigana: "みそしる", arti: "sup miso" },
    { kanji: "焼き魚", furigana: "やきざかな", arti: "ikan bakar" },
    { kanji: "漬け物", furigana: "つけもの", arti: "acar Jepang" },
    { kanji: "毎日", furigana: "まいにち", arti: "setiap hari" },
    { kanji: "少ない", furigana: "すくない", arti: "sedikit" },
    { kanji: "逆", furigana: "ぎゃく", arti: "sebaliknya" },
    { kanji: "西洋風", furigana: "せいようふう", arti: "bergaya Barat" },
    { kanji: "増える", furigana: "ふえる", arti: "bertambah" },
    { kanji: "簡単", furigana: "かんたん", arti: "sederhana" },
    { kanji: "済ませる", furigana: "すませる", arti: "menyelesaikan, mencukupkan" },
    { kanji: "味噌", furigana: "みそ", arti: "pasta kedelai fermentasi" },
    { kanji: "溶かす", furigana: "とかす", arti: "melarutkan" },
    { kanji: "豆腐", furigana: "とうふ", arti: "tahu" },
    { kanji: "具", furigana: "ぐ", arti: "isi, bahan" },
    { kanji: "椀", furigana: "わん", arti: "mangkuk" },
    { kanji: "持つ", furigana: "もつ", arti: "memegang" },
    { kanji: "口", furigana: "くち", arti: "mulut" },
    { kanji: "沈む", furigana: "しずむ", arti: "mengendap, tenggelam" },
    { kanji: "箸", furigana: "はし", arti: "sumpit" },
    { kanji: "軽い", furigana: "かるい", arti: "ringan" },
    { kanji: "混ぜる", furigana: "まぜる", arti: "mencampur" },
    { kanji: "外国", furigana: "がいこく", arti: "luar negeri" },
    { kanji: "病気", furigana: "びょうき", arti: "penyakit" },
    { kanji: "先行", furigana: "せんこう", arti: "mendahului" },
    { kanji: "前提", furigana: "ぜんてい", arti: "prasyarat" },
    { kanji: "洗浄", furigana: "せんじょう", arti: "pencucian" },
    { kanji: "殺菌", furigana: "さっきん", arti: "sterilisasi" },
    { kanji: "行う", furigana: "おこなう", arti: "melakukan" },
    { kanji: "古い", furigana: "ふるい", arti: "lama" },
    { kanji: "安全", furigana: "あんぜん", arti: "aman" },
    { kanji: "出し汁", furigana: "だしじる", arti: "kaldu" },
    { kanji: "卵かけご飯", furigana: "たまごかけごはん", arti: "nasi dengan telur mentah" },
    { kanji: "物", furigana: "もの", arti: "benda, barang" },
    { kanji: "朝", furigana: "あさ", arti: "pagi" },
    { kanji: "外国", furigana: "がいこく", arti: "luar negeri, negara asing" },
    { kanji: "店舗", furigana: "てんぽ", arti: "toko/cabang (konsep umum dari chain store)" },
    { kanji: "定番", furigana: "ていばん", arti: "menu standar, menu populer" },
    { kanji: "地域", furigana: "ちいき", arti: "daerah, wilayah" },
    { kanji: "見つける", furigana: "みつける", arti: "menemukan" },
    { kanji: "食券", furigana: "しょっけん", arti: "tiket makanan" },
    { kanji: "券売機", furigana: "けんばいき", arti: "mesin penjual tiket" },
    { kanji: "会話", furigana: "かいわ", arti: "percakapan" },
    { kanji: "社員食堂", furigana: "しゃいんしょくどう", arti: "kantin karyawan" },
    { kanji: "採用", furigana: "さいよう", arti: "menerapkan, mengadopsi" },
    { kanji: "注文", furigana: "ちゅうもん", arti: "memesan" },
    { kanji: "自動券売機", furigana: "じどうけんばいき", arti: "mesin tiket otomatis" },
    { kanji: "利用", furigana: "りよう", arti: "menggunakan" },
    { kanji: "手順", furigana: "てじゅん", arti: "prosedur" },
    { kanji: "金", furigana: "かね", arti: "uang" },
    { kanji: "押す", furigana: "おす", arti: "menekan" },
    { kanji: "出る", furigana: "でる", arti: "keluar" },
    { kanji: "取る", furigana: "とる", arti: "mengambil" },
    { kanji: "式", furigana: "しき", arti: "tipe, model" },
    { kanji: "方法", furigana: "ほうほう", arti: "metode" },
    { kanji: "商品", furigana: "しょうひん", arti: "produk" },
    { kanji: "受け取る", furigana: "うけとる", arti: "menerima" },
    { kanji: "席", furigana: "せき", arti: "tempat duduk" },
    { kanji: "座る", furigana: "すわる", arti: "duduk" },
    { kanji: "店員", furigana: "てんいん", arti: "pegawai toko" },
    { kanji: "渡す", furigana: "わたす", arti: "menyerahkan" },
    { kanji: "運ぶ", furigana: "はこぶ", arti: "membawa" },
    { kanji: "万円札", furigana: "まんえんさつ", arti: "uang kertas 10.000 yen" },
    { kanji: "千円札", furigana: "せんえんさつ", arti: "uang kertas 1.000 yen" },
    { kanji: "札", furigana: "さつ", arti: "uang kertas" },
    { kanji: "最近", furigana: "さいきん", arti: "akhir-akhir ini" },
    { kanji: "電子決済", furigana: "でんしけっさい", arti: "pembayaran elektronik" },
    { kanji: "居酒屋", furigana: "いざかや", arti: "izakaya, pub/restoran Jepang" },
    { kanji: "豊富", furigana: "ほうふ", arti: "berlimpah, beragam" },
    { kanji: "肉", furigana: "にく", arti: "daging" },
    { kanji: "自由", furigana: "じゆう", arti: "bebas" },
    { kanji: "気軽", furigana: "きがる", arti: "santai, tanpa beban" },
    { kanji: "利用", furigana: "りよう", arti: "menggunakan, memanfaatkan" },
    { kanji: "手順", furigana: "てじゅん", arti: "prosedur, langkah" },
    { kanji: "入り口", furigana: "いりぐち", arti: "pintu masuk" },
    { kanji: "人数", furigana: "にんずう", arti: "jumlah orang" },
    { kanji: "案内", furigana: "あんない", arti: "panduan, mengantar" },
    { kanji: "持つ", furigana: "もつ", arti: "membawa" },
    { kanji: "飲み物", furigana: "のみもの", arti: "minuman" },
    { kanji: "必ず", furigana: "かならず", arti: "pasti, selalu" },
    { kanji: "杯", furigana: "はい", arti: "satuan hitung gelas/cangkir" },
    { kanji: "頼む", furigana: "たのむ", arti: "memesan, meminta" },
    { kanji: "枝豆", furigana: "えだまめ", arti: "edamame" },
    { kanji: "待つ", furigana: "まつ", arti: "menunggu" },
    { kanji: "間", furigana: "あいだ", arti: "selama, ketika" },
    { kanji: "見る", furigana: "みる", arti: "melihat" },
    { kanji: "決める", furigana: "きめる", arti: "memutuskan" },
    { kanji: "追加", furigana: "ついか", arti: "tambahan" },
    { kanji: "呼ぶ", furigana: "よぶ", arti: "memanggil" },
    { kanji: "終わる", furigana: "おわる", arti: "selesai" },
    { kanji: "会計", furigana: "かいけい", arti: "pembayaran, kasir" },
    { kanji: "伝票", furigana: "でんぴょう", arti: "bon, nota" },
    { kanji: "支払い", furigana: "しはらい", arti: "pembayaran" },
    { kanji: "唐揚げ", furigana: "からあげ", arti: "gorengan ala Jepang (umumnya ayam goreng)" },
    { kanji: "食材", furigana: "しょくざい", arti: "bahan makanan" },
    { kanji: "片栗粉", furigana: "かたくりこ", arti: "tepung kentang/tepung pati" },
    { kanji: "薄く", furigana: "うすく", arti: "tipis-tipis" },
    { kanji: "以外", furigana: "いがい", arti: "selain" },
    { kanji: "名", furigana: "めい", arti: "nama" },
    { kanji: "鶏", furigana: "とり", arti: "ayam" },
    { kanji: "骨", furigana: "ほね", arti: "tulang" },
    { kanji: "味付け", furigana: "あじつけ", arti: "memberi bumbu" },
    { kanji: "汁", furigana: "しる", arti: "cairan, sari" },
    { kanji: "代表的", furigana: "だいひょうてき", arti: "representatif, khas" },
    { kanji: "塩辛", furigana: "しおから", arti: "seafood fermentasi asin" },
    { kanji: "冷奴", furigana: "ひややっこ", arti: "tahu dingin" },
    { kanji: "冷やし", furigana: "ひやし", arti: "dingin" },
    { kanji: "新香", furigana: "しんこう", arti: "acar (お新香)" },
    { kanji: "酒", furigana: "さけ", arti: "alkohol" },
    { kanji: "大手", furigana: "おおて", arti: "perusahaan besar" },
    { kanji: "造る", furigana: "つくる", arti: "memproduksi" },
    { kanji: "居酒屋", furigana: "いざかや", arti: "izakaya" },
    { kanji: "宴会", furigana: "えんかい", arti: "jamuan, pesta" },
    { kanji: "最初", furigana: "さいしょ", arti: "pertama" },
    { kanji: "乾杯", furigana: "かんぱい", arti: "bersulang" },
    { kanji: "全員", furigana: "ぜんいん", arti: "semua orang" },
    { kanji: "場合", furigana: "ばあい", arti: "situasi, kasus" },
    { kanji: "飲み始め", furigana: "のみはじめ", arti: "awal minum" },
    { kanji: "役割", furigana: "やくわり", arti: "peran" },
    { kanji: "飲食店", furigana: "いんしょくてん", arti: "restoran" },
    { kanji: "瓶", furigana: "びん", arti: "botol" },
    { kanji: "瓶ビール", furigana: "びんビール", arti: "bir botol" },
    { kanji: "生ビール", furigana: "なまビール", arti: "bir draft" },
    { kanji: "注ぐ", furigana: "そそぐ", arti: "menuangkan" },
    { kanji: "何人", furigana: "なんにん", arti: "berapa orang" },
    { kanji: "大", furigana: "だい", arti: "besar" },
    { kanji: "中", furigana: "ちゅう", arti: "sedang" },
    { kanji: "小", furigana: "しょう", arti: "kecil" },
    { kanji: "量", furigana: "りょう", arti: "jumlah, volume" },
    { kanji: "意味", furigana: "いみ", arti: "arti" },
    { kanji: "全国", furigana: "ぜんこく", arti: "seluruh negeri" },
    { kanji: "地ビール", furigana: "じビール", arti: "bir lokal" },
    { kanji: "旅行", furigana: "りょこう", arti: "perjalanan" },
    { kanji: "楽しい", furigana: "たのしい", arti: "menyenangkan" },
    { kanji: "飲食店", furigana: "いんしょくてん", arti: "restoran, tempat makan" },
    { kanji: "出す", furigana: "だす", arti: "mengeluarkan, menyajikan" },
    { kanji: "小さい", furigana: "ちいさい", arti: "kecil" },
    { kanji: "熱い", furigana: "あつい", arti: "panas" },
    { kanji: "湿らせる", furigana: "しめらせる", arti: "membasahi" },
    { kanji: "客", furigana: "きゃく", arti: "pelanggan" },
    { kanji: "拭く", furigana: "ふく", arti: "mengelap" },
    { kanji: "無料", furigana: "むりょう", arti: "gratis" },
    { kanji: "水道水", furigana: "すいどうすい", arti: "air keran" },
    { kanji: "飲める", furigana: "のめる", arti: "dapat diminum" },
    { kanji: "冷や", furigana: "ひや", arti: "air dingin (お冷や)" },
    { kanji: "願う", furigana: "ねがう", arti: "memohon, meminta" },
    { kanji: "想定", furigana: "そうてい", arti: "asumsi, perkiraan" },
    { kanji: "頼む", furigana: "たのむ", arti: "meminta, memesan" },
    { kanji: "炭酸水", furigana: "たんさんすい", arti: "air berkarbonasi" },
    { kanji: "可能性", furigana: "かのうせい", arti: "kemungkinan" },
    { kanji: "有料", furigana: "ゆうりょう", arti: "berbayar" },
    { kanji: "住宅", furigana: "じゅうたく", arti: "perumahan, tempat tinggal" },
    { kanji: "形", furigana: "かたち", arti: "bentuk" },
    { kanji: "鉄筋", furigana: "てっきん", arti: "rangka baja" },
    { kanji: "造る", furigana: "つくる", arti: "membangun, membuat" },
    { kanji: "大きめ", furigana: "おおきめ", arti: "agak besar" },
    { kanji: "集合住宅", furigana: "しゅうごうじゅうたく", arti: "hunian apartemen/kompleks" },
    { kanji: "部屋", furigana: "へや", arti: "kamar" },
    { kanji: "住む", furigana: "すむ", arti: "tinggal" },
    { kanji: "家賃", furigana: "やちん", arti: "uang sewa" },
    { kanji: "払う", furigana: "はらう", arti: "membayar" },
    { kanji: "借りる", furigana: "かりる", arti: "menyewa" },
    { kanji: "近年", furigana: "きんねん", arti: "beberapa tahun terakhir" },
    { kanji: "都市部", furigana: "としぶ", arti: "daerah perkotaan" },
    { kanji: "建てる", furigana: "たてる", arti: "membangun" },
    { kanji: "土地", furigana: "とち", arti: "tanah" },
    { kanji: "有効利用", furigana: "ゆうこうりよう", arti: "pemanfaatan efektif" },
    { kanji: "高層建築", furigana: "こうそうけんちく", arti: "bangunan bertingkat tinggi" },
    { kanji: "階建て", furigana: "かいだて", arti: "bertingkat" },
    { kanji: "部屋数", furigana: "へやすう", arti: "jumlah kamar" },
    { kanji: "建物", furigana: "たてもの", arti: "bangunan" },
    { kanji: "木造", furigana: "もくぞう", arti: "konstruksi kayu" },
    { kanji: "印象", furigana: "いんしょう", arti: "kesan" },
    { kanji: "法律的", furigana: "ほうりつてき", arti: "secara hukum" },
    { kanji: "明確", furigana: "めいかく", arti: "jelas" },
    { kanji: "区別", furigana: "くべつ", arti: "perbedaan, klasifikasi" },
    { kanji: "一戸建て", furigana: "いっこだて", arti: "rumah tapak/rumah sendiri" },
    { kanji: "郊外", furigana: "こうがい", arti: "pinggiran kota" },
    { kanji: "地方", furigana: "ちほう", arti: "daerah, wilayah" },
    { kanji: "購入", furigana: "こうにゅう", arti: "pembelian" },
    { kanji: "若い", furigana: "わかい", arti: "muda" },
    { kanji: "都心", furigana: "としん", arti: "pusat kota" },
    { kanji: "結婚", furigana: "けっこん", arti: "menikah" },
    { kanji: "場所", furigana: "ばしょ", arti: "tempat" },
    { kanji: "土地", furigana: "とち", arti: "lahan" },
    { kanji: "一軒", furigana: "いっけん", arti: "satu rumah" },
    { kanji: "複数", furigana: "ふくすう", arti: "beberapa, lebih dari satu" },
    { kanji: "賃貸住宅", furigana: "ちんたいじゅうたく", arti: "rumah sewa" },
    { kanji: "個室", furigana: "こしつ", arti: "kamar pribadi" },
    { kanji: "共用", furigana: "きょうよう", arti: "penggunaan bersama" },
    { kanji: "入居者", furigana: "にゅうきょしゃ", arti: "penghuni" },
    { kanji: "共同", furigana: "きょうどう", arti: "bersama-sama" },
    { kanji: "交流", furigana: "こうりゅう", arti: "interaksi" },
    { kanji: "学生", furigana: "がくせい", arti: "mahasiswa, pelajar" },
    { kanji: "寮", furigana: "りょう", arti: "asrama" },
    { kanji: "会社", furigana: "かいしゃ", arti: "perusahaan" },
    { kanji: "社員", furigana: "しゃいん", arti: "karyawan" },
    { kanji: "社員寮", furigana: "しゃいんりょう", arti: "asrama karyawan" },
    { kanji: "学生寮", furigana: "がくせいりょう", arti: "asrama mahasiswa" },
    { kanji: "風呂", furigana: "ふろ", arti: "kamar mandi/bak mandi" },
    { kanji: "割り当てる", furigana: "わりあてる", arti: "mengalokasikan" },
    { kanji: "食事", furigana: "しょくじ", arti: "makanan" },
    { kanji: "食堂", furigana: "しょくどう", arti: "kantin" },
    { kanji: "制服", furigana: "せいふく", arti: "seragam" },
    { kanji: "職場", furigana: "しょくば", arti: "tempat kerja" },
    { kanji: "更衣室", furigana: "こういしつ", arti: "ruang ganti" },
    { kanji: "着替える", furigana: "きがえる", arti: "berganti pakaian" },
    { kanji: "私服", furigana: "しふく", arti: "pakaian pribadi" },
    { kanji: "取り入れる", furigana: "とりいれる", arti: "menerapkan, mengadopsi" },
    { kanji: "工場", furigana: "こうじょう", arti: "pabrik" },
    { kanji: "働く", furigana: "はたらく", arti: "bekerja" },
    { kanji: "際", furigana: "さい", arti: "ketika, pada saat" },
    { kanji: "安全", furigana: "あんぜん", arti: "keselamatan" },
    { kanji: "確保", furigana: "かくほ", arti: "memastikan, mengamankan" },
    { kanji: "作業服", furigana: "さぎょうふく", arti: "pakaian kerja" },
    { kanji: "支給", furigana: "しきゅう", arti: "pemberian, penyediaan" },
    { kanji: "労働者", furigana: "ろうどうしゃ", arti: "pekerja" },
    { kanji: "減らす", furigana: "へらす", arti: "mengurangi" },
    { kanji: "会社外", furigana: "かいしゃがい", arti: "di luar perusahaan" },
    { kanji: "区別", furigana: "くべつ", arti: "membedakan" },
    { kanji: "会社内", furigana: "かいしゃない", arti: "di dalam perusahaan" },
    { kanji: "一体感", furigana: "いったいかん", arti: "rasa kebersamaan" },
    { kanji: "高める", furigana: "たかめる", arti: "meningkatkan" },
    { kanji: "効果", furigana: "こうか", arti: "efek" },
    { kanji: "期待", furigana: "きたい", arti: "harapan" },
    { kanji: "業種", furigana: "ぎょうしゅ", arti: "jenis industri" },
    { kanji: "一定", furigana: "いってい", arti: "terterntu, tetap" },
    { kanji: "服装", furigana: "ふくそう", arti: "cara berpakaian" },
    { kanji: "例える", furigana: "たとえる", arti: "misalnya" },
    { kanji: "金融系", furigana: "きんゆうけい", arti: "bidang keuangan" },
    { kanji: "紺", furigana: "こん", arti: "warna biru tua/navy" },
    { kanji: "濃い", furigana: "こい", arti: "pekat, gelap" },
    { kanji: "黒い", furigana: "くろい", arti: "hitam" },
    { kanji: "革靴", furigana: "かわぐつ", arti: "sepatu kulit" },
    { kanji: "暗黙", furigana: "あんもく", arti: "tersirat" },
    { kanji: "了解", furigana: "りょうかい", arti: "pemahaman, kesepakatan" },
    { kanji: "日本社会", furigana: "にほんしゃかい", arti: "masyarakat Jepang" },
    { kanji: "個性的", furigana: "こせいてき", arti: "individualistik, unik" },
    { kanji: "求める", furigana: "もとめる", arti: "menuntut, mengharapkan" },
    { kanji: "茶", furigana: "ちゃ", arti: "teh" },
    { kanji: "緑茶", furigana: "りょくちゃ", arti: "teh hijau" },
    { kanji: "一般", furigana: "いっぱん", arti: "umum" },
    { kanji: "急須", furigana: "きゅうす", arti: "teko teh Jepang" },
    { kanji: "紅茶", furigana: "こうちゃ", arti: "teh hitam" },
    { kanji: "海外", furigana: "かいがい", arti: "luar negeri" },
    { kanji: "入れる", furigana: "いれる", arti: "memasukkan, menyeduh" },
    { kanji: "麦茶", furigana: "むぎちゃ", arti: "teh barley" },
    { kanji: "大麦", furigana: "おおむぎ", arti: "jelai/barley" },
    { kanji: "店", furigana: "みせ", arti: "toko/restoran" },
    { kanji: "抹茶", furigana: "まっちゃ", arti: "matcha" },
    { kanji: "葉", furigana: "は", arti: "daun" },
    { kanji: "粉", furigana: "こな", arti: "bubuk" },
    { kanji: "茶道", furigana: "さどう", arti: "upacara minum teh" },
    { kanji: "菓子", furigana: "かし", arti: "makanan manis, kue" },
    { kanji: "材料", furigana: "ざいりょう", arti: "bahan" },
    { kanji: "原産", furigana: "げんさん", arti: "berasal dari" },
    { kanji: "半分", furigana: "はんぶん", arti: "setengah" },
    { kanji: "茶色", furigana: "ちゃいろ", arti: "warna cokelat" },
    { kanji: "渋み", furigana: "しぶみ", arti: "rasa sepat" },
    { kanji: "何種類", furigana: "なんしゅるい", arti: "beberapa jenis" },
    { kanji: "砂糖", furigana: "さとう", arti: "gula" },
    { kanji: "甘い", furigana: "あまい", arti: "manis" },
    { kanji: "合う", furigana: "あう", arti: "cocok" },
    { kanji: "送信元", furigana: "そうしんもと", arti: "pengirim" },
    { kanji: "画像", furigana: "がぞう", arti: "gambar" },
    { kanji: "変換", furigana: "へんかん", arti: "konversi" },
    { kanji: "電話回線", furigana: "でんわかいせん", arti: "saluran telepon" },
    { kanji: "通じる", furigana: "つうじる", arti: "melalui" },
    { kanji: "送る", furigana: "おくる", arti: "mengirim" },
    { kanji: "送信先", furigana: "そうしんさき", arti: "penerima" },
    { kanji: "紙", furigana: "かみ", arti: "kertas" },
    { kanji: "印刷", furigana: "いんさつ", arti: "mencetak" },
    { kanji: "機械", furigana: "きかい", arti: "mesin" },
    { kanji: "年代", furigana: "ねんだい", arti: "dekade" },
    { kanji: "普及", furigana: "ふきゅう", arti: "penyebaran" },
    { kanji: "現役", furigana: "げんえき", arti: "masih aktif digunakan" },
    { kanji: "関係", furigana: "かんけい", arti: "hubungan, terkait" },
    { kanji: "通知", furigana: "つうち", arti: "pemberitahuan" },
    { kanji: "連絡", furigana: "れんらく", arti: "kontak, komunikasi" },
    { kanji: "今", furigana: "いま", arti: "sekarang" },
    { kanji: "手書き", furigana: "てがき", arti: "tulisan tangan" },
    { kanji: "書類", furigana: "しょるい", arti: "dokumen" },
    { kanji: "信用", furigana: "しんよう", arti: "kepercayaan" },
    { kanji: "挙げる", furigana: "あげる", arti: "mengemukakan" },
    { kanji: "手続き", furigana: "てつづき", arti: "prosedur" },
    { kanji: "認める", furigana: "みとめる", arti: "mengizinkan, mengakui" },
    { kanji: "受け付ける", furigana: "うけつける", arti: "menerima, memproses" },
    { kanji: "朝礼", furigana: "ちょうれい", arti: "apel pagi, briefing pagi" },
    { kanji: "企業", furigana: "きぎょう", arti: "perusahaan" },
    { kanji: "始まる", furigana: "はじまる", arti: "dimulai" },
    { kanji: "従業員", furigana: "じゅうぎょういん", arti: "karyawan" },
    { kanji: "集まる", furigana: "あつまる", arti: "berkumpul" },
    { kanji: "連絡", furigana: "れんらく", arti: "pemberitahuan, komunikasi" },
    { kanji: "行う", furigana: "おこなう", arti: "melaksanakan" },
    { kanji: "目的", furigana: "もくてき", arti: "tujuan" },
    { kanji: "流れ", furigana: "ながれ", arti: "alur" },
    { kanji: "特別", furigana: "とくべつ", arti: "khusus" },
    { kanji: "注意事項", furigana: "ちゅういじこう", arti: "hal-hal yang perlu diperhatikan" },
    { kanji: "顔", furigana: "かお", arti: "wajah" },
    { kanji: "合わせる", furigana: "あわせる", arti: "saling bertemu" },
    { kanji: "切り替える", furigana: "きりかえる", arti: "mengalihkan, mengganti mode" },
    { kanji: "体操", furigana: "たいそう", arti: "senam" },
    { kanji: "取り入れる", furigana: "とりいれる", arti: "menerapkan" },
    { kanji: "番組", furigana: "ばんぐみ", arti: "program acara" },
    { kanji: "子ども", furigana: "こども", arti: "anak-anak" },
    { kanji: "身近", furigana: "みぢか", arti: "dekat dengan kehidupan sehari-hari" },
    { kanji: "存在", furigana: "そんざい", arti: "keberadaan" },
    { kanji: "労働", furigana: "ろうどう", arti: "kerja, tenaga kerja" },
    { kanji: "体", furigana: "からだ", arti: "tubuh" },
    { kanji: "慣れさせる", furigana: "なれさせる", arti: "membiasakan" },
    { kanji: "意図", furigana: "いと", arti: "maksud, tujuan" },
    { kanji: "公営", furigana: "こうえい", arti: "milik/pengelolaan pemerintah" },
    { kanji: "屋外", furigana: "おくがい", arti: "luar ruangan" },
    { kanji: "時期", furigana: "じき", arti: "periode, musim" },
    { kanji: "市", furigana: "し", arti: "kota" },
    { kanji: "区", furigana: "く", arti: "distrik" },
    { kanji: "数百円", furigana: "すうひゃくえん", arti: "beberapa ratus yen" },
    { kanji: "利用料", furigana: "りようりょう", arti: "biaya penggunaan" },
    { kanji: "自治体", furigana: "じちたい", arti: "pemerintah daerah" },
    { kanji: "在住", furigana: "ざいじゅう", arti: "tinggal (domisili)" },
    { kanji: "在勤", furigana: "ざいきん", arti: "bekerja di wilayah tersebut" },
    { kanji: "開放", furigana: "かいほう", arti: "dibuka untuk umum" },
    { kanji: "決まる", furigana: "きまる", arti: "ditentukan" },
    { kanji: "思う", furigana: "おもう", arti: "berpikir" },
    { kanji: "調べる", furigana: "しらべる", arti: "mencari, memeriksa" },
    { kanji: "必ず", furigana: "かならず", arti: "wajib" },
    { kanji: "日焼け止め", furigana: "ひやけどめ", arti: "tabir surya" },
    { kanji: "禁止", furigana: "きんし", arti: "dilarang" },
    { kanji: "注意", furigana: "ちゅうい", arti: "perhatian" },
    { kanji: "必要", furigana: "ひつよう", arti: "perlu" },
    { kanji: "映画", furigana: "えいが", arti: "film" },
    { kanji: "見る", furigana: "みる", arti: "menonton" },
    { kanji: "映画館", furigana: "えいがかん", arti: "bioskop" },
    { kanji: "方法", furigana: "ほうほう", arti: "cara" },
    { kanji: "数年", furigana: "すうねん", arti: "beberapa tahun" },
    { kanji: "大きく", furigana: "おおきく", arti: "secara besar" },
    { kanji: "変わる", furigana: "かわる", arti: "berubah" },
    { kanji: "以前", furigana: "いぜん", arti: "dahulu" },
    { kanji: "上映", furigana: "じょうえい", arti: "pemutaran film" },
    { kanji: "決める", furigana: "きめる", arti: "menentukan" },
    { kanji: "一定", furigana: "いってい", arti: "tetap" },
    { kanji: "期間", furigana: "きかん", arti: "periode" },
    { kanji: "繰り返し", furigana: "くりかえし", arti: "berulang-ulang" },
    { kanji: "客", furigana: "きゃく", arti: "penonton" },
    { kanji: "都合", furigana: "つごう", arti: "kecocokan jadwal" },
    { kanji: "回", furigana: "かい", arti: "sesi, putaran" },
    { kanji: "座席", furigana: "ざせき", arti: "kursi" },
    { kanji: "自由席", furigana: "じゆうせき", arti: "kursi bebas" },
    { kanji: "形式", furigana: "けいしき", arti: "bentuk, format" },
    { kanji: "主流", furigana: "しゅりゅう", arti: "arus utama" },
    { kanji: "複数", furigana: "ふくすう", arti: "beberapa" },
    { kanji: "部屋", furigana: "へや", arti: "ruangan" },
    { kanji: "割り振る", furigana: "わりふる", arti: "mengalokasikan" },
    { kanji: "公開", furigana: "こうかい", arti: "rilis" },
    { kanji: "指定席", furigana: "していせき", arti: "kursi bernomor" },
    { kanji: "料金", furigana: "りょうきん", arti: "biaya" },
    { kanji: "大人", furigana: "おとな", arti: "orang dewasa" },
    { kanji: "円", furigana: "えん", arti: "yen" },
    { kanji: "別料金", furigana: "べつりょうきん", arti: "biaya tambahan" },
    { kanji: "映画の日", furigana: "えいがのひ", arti: "Hari Film" },
    { kanji: "割引", furigana: "わりびき", arti: "diskon" },
    { kanji: "会員", furigana: "かいいん", arti: "anggota" },
    { kanji: "当日", furigana: "とうじつ", arti: "hari itu" },
    { kanji: "説明", furigana: "せつめい", arti: "penjelasan" }
];